name: Publish

on:
  workflow_run:
    workflows: ["Version and Tag"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: https://npm.moisa.work/
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          registry-url: ${{ env.REGISTRY_URL }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish package
        run: pnpm publish --registry $REGISTRY_URL --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
